steps:
  install:
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run:
        - prepare
      with: npm
  release:
    image: plugins/npm
    settings:
      token:
        from_secret: npm_access_token
      access: public
when:
  event: tag
  ref: refs/tags/v*
