pipeline:
  install:
    image: danlynn/ember-cli:4.7.0-node_16.17
    commands:
      - npm ci
  lint:js:
    image: danlynn/ember-cli:4.7.0-node_16.17
    commands:
      - npm run lint:js
  test:
    image: danlynn/ember-cli:4.7.0-node_16.17
    commands:
      - npm run test
when:
  event: pull_request
