pipeline:
  install:
    image: woodpeckerci/plugin-node-pm
    commands: 
      - npm ci
  verify:
    image: woodpeckerci/plugin-node-pm
    settings:
      run:
        - format
        - lint:js
        - test || exit 0
        - build # script name
      frozen_lockfile: true # recommended
      ignore_node_modules: true # recommended
when:
  event: pull_request
