pipeline:
  install:
    image: danlynn/ember-cli:4.4.0
    commands:
      - npm ci
  format:
    image: danlynn/ember-cli:4.4.0
    commands:
      - npm run format
  lint:
    image: danlynn/ember-cli:4.4.0
    group: lint
    commands:
      - npm run lint:js
  test:
    image: danlynn/ember-cli:4.4.0
    commands:
      - npm run test || exit 0
  build:
    image: danlynn/ember-cli:4.4.0
    commands:
      - npm run build
when:
  event: pull_request
